### ISSUE TITLE
epsg code

### ISSUE THREAD

**Issue by dslramsey** [eradicate-dev/poaShiny#2]
Most users will not know epsg codes for their spatial data.  However, epsg codes are currently required by the python code.  One way of overcoming this is to extract the epsg code from the initial extent shapefile with st_crs(extent)$epsg and then set the epsg input field in the UI with this value.   This can then be used to transform any other spatial data (rasters etc).   However, it requires that the initial extent have a non missing crs() when uploaded.   I think we just make this a condition in the docs.  

The latest push to devel has an observeEvent that extracts the epsg code.  However, this doesn't seem to work for the example extents as the crs() seems to be missing from these files.

**Comment by sihoward** [comment]
I pulled the enhancement into the latest branch. It works locally, but not on shinyapps.io. The spatial libraries on shinyapps.io (https://docs.rstudio.com/shinyapps.io/appendix.html#additional-resources) are earlier than the version currently used in sf (at least on Windows). Maybe just extract the wkt string for the shape file and apply to all other uploaded files?

**Comment by dslramsey** [comment]
OK maybe do whatever you need to to get it to work on shinyapps.io.  At least for the workshop.  I just had a play with this locally and all looked good except that the device locations didn't plot on the map?
